
        
      CREATE TABLE IF NOT EXISTS hospitals(id TEXT PRIMARY KEY,name TEXT NOT NULL,address TEXT NOT NULL DEFAULT '',phone TEXT NOT NULL DEFAULT '',"upiId" TEXT NOT NULL DEFAULT '',"payeeName" TEXT NOT NULL DEFAULT '');
      CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,role TEXT NOT NULL CHECK(role IN ('patient','hospital')),name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,mobile TEXT NOT NULL,password TEXT NOT NULL,"hospitalId" TEXT REFERENCES hospitals(id),"createdAt" TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS sessions(hash TEXT PRIMARY KEY,"userId" TEXT NOT NULL REFERENCES users(id),expires BIGINT NOT NULL);
      CREATE TABLE IF NOT EXISTS limits(key TEXT PRIMARY KEY,count INTEGER NOT NULL,until BIGINT NOT NULL);
      CREATE TABLE IF NOT EXISTS services(id TEXT PRIMARY KEY,"hospitalId" TEXT NOT NULL REFERENCES hospitals(id),name TEXT NOT NULL,prefix TEXT NOT NULL,price INTEGER NOT NULL DEFAULT 0,minutes INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'closed',sequence INTEGER NOT NULL DEFAULT 0,streak INTEGER NOT NULL DEFAULT 0);
      CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,"userId" TEXT NOT NULL REFERENCES users(id),"hospitalId" TEXT NOT NULL REFERENCES hospitals(id),"serviceId" TEXT NOT NULL REFERENCES services(id),amount INTEGER NOT NULL,priority TEXT NOT NULL,name TEXT NOT NULL,mobile TEXT NOT NULL,"smsConsent" INTEGER NOT NULL,status TEXT NOT NULL,"gatewayId" TEXT UNIQUE,"keyId" TEXT,"paymentId" TEXT UNIQUE,"tokenId" TEXT UNIQUE,"createdAt" TEXT NOT NULL,"requestKey" TEXT NOT NULL,UNIQUE("userId","requestKey"));
      CREATE TABLE IF NOT EXISTS tokens(id TEXT PRIMARY KEY,"orderId" TEXT NOT NULL UNIQUE REFERENCES orders(id),"userId" TEXT NOT NULL REFERENCES users(id),"hospitalId" TEXT NOT NULL REFERENCES hospitals(id),"serviceId" TEXT NOT NULL REFERENCES services(id),number TEXT NOT NULL,priority TEXT NOT NULL,status TEXT NOT NULL,"createdAt" TEXT NOT NULL,"calledAt" TEXT,"completedAt" TEXT,UNIQUE("serviceId",number));
      CREATE UNIQUE INDEX IF NOT EXISTS one_called ON tokens("serviceId") WHERE status='called';
      CREATE TABLE IF NOT EXISTS sms("tokenId" TEXT PRIMARY KEY REFERENCES tokens(id),status TEXT NOT NULL,sid TEXT,error TEXT,attempts INTEGER NOT NULL DEFAULT 0,"updatedAt" TEXT NOT NULL);
      CREATE INDEX IF NOT EXISTS tokens_queue ON tokens("serviceId",status,"createdAt");
      CREATE INDEX IF NOT EXISTS orders_user ON orders("userId","createdAt");
    
CREATE TABLE IF NOT EXISTS payment_settings("hospitalId" TEXT PRIMARY KEY REFERENCES hospitals(id),"keyId" TEXT NOT NULL,encrypted TEXT NOT NULL,"verifiedAt" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS payment_settings_history("hospitalId" TEXT NOT NULL REFERENCES hospitals(id),"keyId" TEXT NOT NULL,encrypted TEXT NOT NULL,PRIMARY KEY("hospitalId","keyId"));
ALTER TABLE hospitals ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE sms ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_settings_history ENABLE ROW LEVEL SECURITY;